### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by JCBrouwer** [keijiro/Ngx#1]
Hello, this looks amazing, but I can't seem to get it working. I'm running macOS Sierra with a GTX 1080 Ti.

When I run the app from the releases page all I get is a black screen. None of the buttons/knobs change anything except for FColor, Hue Shift, and Invert which only make a colorful glow appear around the edge of the canvas. There doesn't seem to be any pix2pix'ing.

I've also tried opening the project in Unity, but I have no experience at all with the program and I can't seem to get any results here either (I've copied the .pict files from the app). I get 2 errors in the console as soon as I start up:

> /Users/hans/Library/Unity/cache/packages/packages.unity.com/com.unity.package-manager-ui@2.0.2/Editor/Sources/Services/Upm/UpmBaseOperation.cs(33,34): error CS1061: Type 'UnityEditor.PackageManager.PackageInfo' does not contain a definition for `author' and no extension method 'author' of type 'UnityEditor.PackageManager.PackageInfo' could be found. Are you missing an assembly reference?

>'Reflection Probes' job failed with error code: 2 ('Failed to bake the skybox probe.').

Once I click play at the top I get 200 errors saying that scripts are missing. Looking around through the hierarchy does indeed show a lot of scripts that cannot be compiled / loaded. I've added [MidiJack](https://github.com/keijiro/MidiJack) and [PostProcessing](https://github.com/Unity-Technologies/PostProcessing), are there any other dependencies I'm missing? It would be nice to add all the Unity dependencies to the README. Even with these added, many scripts that rely on these packages don't seem to compile / load, despite there being no import errors shown anymore when opening the scripts.

Most objects in the hierarchy seem to refer to unloadable scripts that are in the Script folder of the project except for the objects in the 'Controller' part of the hierarchy (Model 1-8, Feedback, False Color, etc.) which reference just a 'Missing (Mono Script)'.

How can the MIDI maps be changed to work for different MIDI controllers? I've taken a peek around the MIDI*EventReceivers but could not see anything that was looking for specific MIDI CCs.

What are the steps I need to follow to get a working version in Unity?

Also, is there an easy way to convert PyTorch models to .pict files?

Finally, how difficult would it be to get something similar running based on OpenGL & PyTorch/Tensorflow instead of Unity? Are there any serious optimizations that are Unity/C# specific?

Really excited to try this out, thanks!

**Comment by keijiro** [comment]
First of all, please try moving the extracted files to Desktop or Applications before launching it? I guess it failed to load the model files due to [App Translocation](https://lapcatsoftware.com/articles/app-translocation.html) on macOS.

To open the project in Unity, you have to check [submodules](https://blog.github.com/2016-02-01-working-with-submodules/) out. I'd recommend removing the working directory and re-clone the repository with `--recursive` option.

I think there is no instant way to export `.pict` files from the PyTorch version of pix2pix. You have to port the [`pix2pix export`](https://colab.research.google.com/drive/1Dc3E6GJ4jjlBIJLaJd--FgKFQGpa_O5N) script to PyTorch by yourself.

Regarding the possibilities to run it outside Unity, I think your idea is similar to what [@quasimondo](https://twitter.com/quasimondo) does. If I remember correctly, he's using an OpenGL based host and multiple PyTorch worker machines. It would work if you're familiar with these frameworks rather than Unity.

**Comment by keijiro** [comment]
FYI, I added "How to open the project in Unity" section to README.

**Comment by JCBrouwer** [comment]
Thank you for the quick response!

I've tried moving the .app to my Applications folder but no joy. Still only the color vignette is showing.

I also recloned the repository with the submodules (d'oh!) and I'm still getting the 2 errors mentioned above as well as the following error in knob.cs and button.cs:

> error CS0117: 'UnityEditor.PrefabUtility' does not contain a definition for 'IsPartOfPrefabAsset'

**Comment by keijiro** [comment]
Okay. Then could you send the player log file? (~/Library/Logs/Unity/Player.log)

From the error message, it seems you're using previous version of Unity. Please use the latest beta version of Unity (2018.3.0b5 or later).

**Comment by JCBrouwer** [comment]
Yes! Upgrading Unity to 2018.3.0b6 worked!

I've been able to get it up and running with my own models and MIDI controller as well. Runs ~30 fps on my system with quite a bit of other random applications open + screen capture.

Thanks so much for this awesome bit of software @keijiro !

![gif](https://i.imgur.com/D4tsQXB.gif)

Next up I'll see if I can export PyTorch models to .pict files.
